package src;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author OJT
 */
public class branches extends javax.swing.JFrame {

    int id;
    
    
    /**
     * Creates new form branches
     */
    public branches() {
        initComponents();
    }

 


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        branch = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        code = new javax.swing.JTextField();
        close_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(82, 115, 77));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SSM BRANCHES");

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Branches:");

        branch.setBackground(new java.awt.Color(0, 0, 0));
        branch.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        branch.setForeground(new java.awt.Color(255, 255, 255));

        save_btn.setBackground(new java.awt.Color(0, 153, 0));
        save_btn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("SAVE");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        update_btn.setBackground(new java.awt.Color(0, 153, 153));
        update_btn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(204, 0, 0));
        delete_btn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        view_btn.setBackground(new java.awt.Color(255, 255, 0));
        view_btn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        view_btn.setText("View");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Branch Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(0, 204, 204));
        table.setShowGrid(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(60);
            table.getColumnModel().getColumn(0).setPreferredWidth(400);
            table.getColumnModel().getColumn(0).setMaxWidth(140);
        }

        code.setBackground(new java.awt.Color(0, 0, 0));
        code.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        code.setForeground(new java.awt.Color(255, 255, 255));
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(code, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(branch, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(0, 672, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn)
                    .addComponent(update_btn)
                    .addComponent(delete_btn)
                    .addComponent(view_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        close_btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 0, 0));
        close_btn.setText("X");
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(323, 323, 323)
                .addComponent(close_btn)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addComponent(close_btn))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
//
//        if(JOptionPane.showConfirmDialog(close_btn,"Do you want to exit?","Close",
//            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
//
//     
//        }
           System.exit(0);
    }//GEN-LAST:event_close_btnMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        company c = new company();
        dispose();
        c.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
     
   
 if(branch.getText().equals("Baliwag")){
     
     Baliuag B = new Baliuag();
     B.setVisible(true);
     dispose();
} else if(branch.getText().equals("Pasig City")){
            
     Main M = new Main();
     M.setVisible(true);
         dispose();
     }
     else if(branch.getText().equals("Makati")){
            
     Makati mak
             = new Makati();
     mak.setVisible(true);
         dispose();
     }
else{
       if(branch.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Please Select Company");
}
}
 
    
//         int i = table.getSelectedRow();
//        TableModel model = table.getModel();
//         code.setText(model.getValueAt(i,0).toString());
//        branch.setText(model.getValueAt(i,1).toString());
//        
//       

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
//       
//        try  {
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_system", "root", "");
//           Class.forName("com.mysql.cj.jdbc.Driver");  
//           Statement st = conn.createStatement();
//           String sql = "select * from branches";
//           ResultSet res = st.executeQuery(sql);
////           ResultSet res=st.executeQuery("SELECT * FROM branches");
////           res.last();
////           int row=res.getRow();
////           int col=res.getMetaData().getColumnCount();
////           res.beforeFirst();
////           String rowData[][]= new String[row][col];
////           int r=0;
//           while(res.next()){
//               
//
//               String branch_name = res.getString("branches_name");
//               String tbData[] = {branch_name};
//               
//                 DefaultTableModel model = (DefaultTableModel)table.getModel();
//                 model.addRow(tbData);
////               for(int i=0; i<col;i++){
//////                   rowData[r][i]=res.getString(i+1);
//////               }
////               r++;
//           }
////           String[] columnName = {"ID","Branch Name"};
////           DefaultTableModel model = (DefaultTableModel)table.getModel();
////           model.setDataVector(rowData, columnName);
//        
//               
//       }
//        catch (ClassNotFoundException | SQLException e)
//         {
//            System.err.println("Got an exception!");
//            System.err.println(e.getMessage());
//         } 
    }//GEN-LAST:event_view_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
         String ssm = "SSM"; 
        String br = branch.getText();
  
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           
                if(branch.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Enter Branch Name");
} else {
            
            
          String query = " insert into branches (code,branches_name)"+" values (?,?)";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString (1, ssm);
             preparedStmt.setString (2, br);
           JOptionPane.showMessageDialog(this, "Branch inserted");
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           branches branch1 = new branches();
           branch1.setVisible(true);
           dispose();
         }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
    }//GEN-LAST:event_save_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   

         try  {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_system", "root", "");
           Class.forName("com.mysql.cj.jdbc.Driver");  
           Statement st = conn.createStatement();
           String sql = "select * from branches";
           ResultSet res = st.executeQuery(sql);
//           ResultSet res=st.executeQuery("SELECT * FROM branches");
//           res.last();
//           int row=res.getRow();
//           int col=res.getMetaData().getColumnCount();
//           res.beforeFirst();
//           String rowData[][]= new String[row][col];
//           int r=0;
           while(res.next()){
               
//               String id = String.valueOf(res.getInt("id"));
               String ssm = res.getString("code");
                  String branch_name = res.getString("branches_name");
               String tbData[] = {ssm,branch_name};
               
                 DefaultTableModel model = (DefaultTableModel)table.getModel();
                 model.addRow(tbData);
//               for(int i=0; i<col;i++){
////                   rowData[r][i]=res.getString(i+1);
////               }
//               r++;
           }
//           String[] columnName = {"ID","Branch Name"};
//           DefaultTableModel model = (DefaultTableModel)table.getModel();
//           model.setDataVector(rowData, columnName);
        
               
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         } 
    }//GEN-LAST:event_formWindowOpened

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int i = table.getSelectedRow();
         code.setText(model.getValueAt(i,0).toString());
        branch.setText(model.getValueAt(i,1).toString());
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

         
        int i=table.getSelectedRow();
       if(i>=0){
           DefaultTableModel model = (DefaultTableModel)table.getModel();
          JFrame delete_btn;
       delete_btn = new JFrame("EXIT");
           if(JOptionPane.showConfirmDialog(delete_btn,"Do you want to to Delete?","MySQL Connector",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
              model.removeRow(i);
       }
       }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
    DefaultTableModel model = (DefaultTableModel)table.getModel();
        int i = table.getSelectedRow();
  
       try{
           
           id = Integer.parseInt(model.getValueAt(i, 0).toString());
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           
                if(branch.getText().equals("")||code.getText().equals("")){
                 JOptionPane.showMessageDialog(null,"Select Branch Name");
} else {
            
            
      
            
            // create the mysql update preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement("update branches set code=?, branches_name=? where id=?");
            preparedStmt.setString (1, code.getText());
             preparedStmt.setString (2, branch.getText());
           Statement st = conn.createStatement();
           preparedStmt.execute();
              JOptionPane.showMessageDialog(this, "Branch Updated");
          
         }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
    }//GEN-LAST:event_update_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(branches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(branches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(branches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(branches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new branches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branch;
    private javax.swing.JLabel close_btn;
    public javax.swing.JTextField code;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save_btn;
    private javax.swing.JTable table;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
