package src;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author OJT
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    
        table1.getColumnModel().getColumn(1).setPreferredWidth(200);
        table2.getColumnModel().getColumn(1).setPreferredWidth(200);
        table3.getColumnModel().getColumn(1).setPreferredWidth(200);
        table4.getColumnModel().getColumn(1).setPreferredWidth(200);
        
        JTableHeader Threader = table1.getTableHeader();
        Threader.setBackground(Color.red);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        an = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        sales = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        selecting_table = new javax.swing.JComboBox<>();
        selecting = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        save_btn2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        save_btn3 = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        table1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Product Name", "Article No.", "Stocks", "Price", "Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setRowHeight(25);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel7.setText("Flavoring");

        table2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Food Color", "Article No.", "Stocks", "Price", "Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.setRowHeight(25);
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table2);
        table2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table2.getColumnModel().getColumnCount() > 0) {
            table2.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel8.setText("GL Mixes");

        table3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "GL Mixes", "Article No.", "Stocks", "Price", "Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table3.setRowHeight(25);
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(table3);
        table3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table3.getColumnModel().getColumnCount() > 0) {
            table3.getColumnModel().getColumn(1).setResizable(false);
        }

        table4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Special Flavor", "Article No.", "Stocks", "Price", "Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table4.setDropMode(javax.swing.DropMode.INSERT);
        table4.setRowHeight(25);
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(table4);
        table4.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table4.getColumnModel().getColumnCount() > 0) {
            table4.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel9.setText("Food Color");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel10.setText("Special Flavor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Article No:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stocks:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sales:");

        save_btn.setBackground(new java.awt.Color(0, 102, 255));
        save_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("Save");
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        selecting_table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selecting_table.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "table1", "table2", "table3", "table4" }));
        selecting_table.setToolTipText("");
        selecting_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selecting_table.setName(""); // NOI18N
        selecting_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecting_tableActionPerformed(evt);
            }
        });

        selecting.setForeground(new java.awt.Color(0, 0, 102));

        update.setBackground(new java.awt.Color(0, 0, 102));
        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        save_btn2.setBackground(new java.awt.Color(153, 0, 0));
        save_btn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save_btn2.setForeground(new java.awt.Color(255, 255, 255));
        save_btn2.setText("Delete");
        save_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btn2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(0, 51, 153));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pasig City Branch");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        save_btn3.setBackground(new java.awt.Color(0, 102, 102));
        save_btn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save_btn3.setForeground(new java.awt.Color(255, 255, 255));
        save_btn3.setText("Back");
        save_btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btn3ActionPerformed(evt);
            }
        });

        reset_btn.setBackground(new java.awt.Color(153, 0, 153));
        reset_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("Reset");
        reset_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selecting_table, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p)
                            .addComponent(s, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(an, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn)
                            .addComponent(no, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sales, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(selecting, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset_btn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addComponent(selecting_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(selecting, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn)
                    .addComponent(update)
                    .addComponent(save_btn2)
                    .addComponent(save_btn3)
                    .addComponent(reset_btn))
                .addGap(222, 222, 222))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
       
       String n = no.getText();
       String product_name = pn.getText();
       String article = an.getText();
       String stocks = s.getText();
       String price = p.getText();
       String sale = sales.getText();
       
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
            
//              selecting.setText(selectedValue);
           
                if(no.getText().equals("")|| pn.getText().equals("") ||an.getText().equals("") ||s.getText().equals("") ||p.getText().equals("") ||sales.getText().equals("")){
                     JOptionPane.showMessageDialog(null,"Please Fill Complete Information");
                }
//                else if(pn.getText().equals("")){
//                     JOptionPane.showMessageDialog(null,"Enter Product Name");
//                }
//                else if(an.getText().equals("")){
//                     JOptionPane.showMessageDialog(null,"Enter Article Number");
//                }
//                else if(s.getText().equals("")){
//                     JOptionPane.showMessageDialog(null,"Enter Stocks");
//                }
//                else if(p.getText().equals("")){
//                     JOptionPane.showMessageDialog(null,"Enter Price");
//                }
//                else if(sales.getText().equals("")){
//                     JOptionPane.showMessageDialog(null,"Enter Sales");
//                }
                
                else if(selecting.getText().equals("select")){
                     JOptionPane.showMessageDialog(null,"Select Table");
                }
                else if(selecting.getText().equals("table1")){
                
            
                    String query = " insert into flavoring (number,product_name,article_no,stocks,price,sales)"+" values (?,?,?,?,?,?)";

                      // create the mysql insert preparedstatement
                      PreparedStatement preparedStmt = conn.prepareStatement(query);
                       preparedStmt.setString (1, n);
                      preparedStmt.setString (2, product_name);
                      preparedStmt.setString (3, article);
                      preparedStmt.setString (4, stocks);
                      preparedStmt.setString (5, price);
                      preparedStmt.setString (6, sale);
                     JOptionPane.showMessageDialog(this, "Flavoring Inserted");
                     Statement st = conn.createStatement();
                     preparedStmt.execute();

                     Main m = new Main();
                     m.setVisible(true);
                     dispose();
                }
               else if(selecting.getText().equals("table2")){
                
            
                    String query = " insert into food_color (number,color,article_no,stocks,price,sales)"+" values (?,?,?,?,?,?)";

                      // create the mysql insert preparedstatement
                      PreparedStatement preparedStmt = conn.prepareStatement(query);
                       preparedStmt.setString (1, n);
                      preparedStmt.setString (2, product_name);
                      preparedStmt.setString (3, article);
                      preparedStmt.setString (4, stocks);
                      preparedStmt.setString (5, price);
                      preparedStmt.setString (6, sale);
                     JOptionPane.showMessageDialog(this, "Food Color Inserted");
                     Statement st = conn.createStatement();
                     preparedStmt.execute();

                     Main m = new Main();
                     m.setVisible(true);
                     dispose();
                } 
                else if(selecting.getText().equals("table3")){
                
            
                    String query = " insert into gl_mixes (number,product_name1,article_no,stocks,price,sales)"+" values (?,?,?,?,?,?)";

                      // create the mysql insert preparedstatement
                      PreparedStatement preparedStmt = conn.prepareStatement(query);
                       preparedStmt.setString (1, n);
                      preparedStmt.setString (2, product_name);
                      preparedStmt.setString (3, article);
                      preparedStmt.setString (4, stocks);
                      preparedStmt.setString (5, price);
                      preparedStmt.setString (6, sale);
                     JOptionPane.showMessageDialog(this, "GL MIXES Inserted");
                     Statement st = conn.createStatement();
                     preparedStmt.execute();

                     Main m = new Main();
                     m.setVisible(true);
                     dispose();
                } 
                else if(selecting.getText().equals("table4")){
                
            
                    String query = " insert into special_flavor (number,product_name,article_no,stocks,price,sales)"+" values (?,?,?,?,?,?)";

                      // create the mysql insert preparedstatement
                      PreparedStatement preparedStmt = conn.prepareStatement(query);
                       preparedStmt.setString (1, n);
                      preparedStmt.setString (2, product_name);
                      preparedStmt.setString (3, article);
                      preparedStmt.setString (4, stocks);
                      preparedStmt.setString (5, price);
                      preparedStmt.setString (6, sale);
                     JOptionPane.showMessageDialog(this, "Special Flavor Inserted");
                     Statement st = conn.createStatement();
                     preparedStmt.execute();

                     Main m = new Main();
                     m.setVisible(true);
                     dispose();
                } 
                
                else {
                    JOptionPane.showMessageDialog(null, "Can't add the product");
                }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
    }//GEN-LAST:event_save_btnActionPerformed

    private void selecting_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecting_tableActionPerformed
      String selectedValue = selecting_table.getSelectedItem().toString();
     selecting.setText(selectedValue);
    }//GEN-LAST:event_selecting_tableActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try  {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_system", "root", "");
           Class.forName("com.mysql.cj.jdbc.Driver");  
           Statement st = conn.createStatement();
           String sql = "select * from flavoring";
           ResultSet res = st.executeQuery(sql);
//           ResultSet res=st.executeQuery("SELECT * FROM branches");
//           res.last();
//           int row=res.getRow();
//           int col=res.getMetaData().getColumnCount();
//           res.beforeFirst();
//           String rowData[][]= new String[row][col];
//           int r=0;
           while(res.next()){
               
//               String id = String.valueOf(res.getInt("id"));
               String n = res.getString("number");
               String product_name = res.getString("product_name");
               String article = res.getString("article_no");
               String stocks = res.getString("stocks");
               String price = res.getString("price");
               String sale = res.getString("sales");
               String tbData[] = {n,product_name,article,stocks,price,sale};
               
                 DefaultTableModel model = (DefaultTableModel)table1.getModel();
                 model.addRow(tbData);
//               for(int i=0; i<col;i++){
////                   rowData[r][i]=res.getString(i+1);
////               }
//               r++;
           }
             Statement st1 = conn.createStatement();
           String sql1 = "select * from food_color";
           ResultSet res1 = st1.executeQuery(sql1);
             while(res1.next()){
               
//               String id = String.valueOf(res.getInt("id"));
               String n = res1.getString("number");
               String product_name = res1.getString("color");
               String article = res1.getString("article_no");
               String stocks = res1.getString("stocks");
               String price = res1.getString("price");
               String sale = res1.getString("sales");
               String tbData[] = {n,product_name,article,stocks,price,sale};
               
                 DefaultTableModel model = (DefaultTableModel)table2.getModel();
                 model.addRow(tbData);
//               for(int i=0; i<col;i++){
////                   rowData[r][i]=res.getString(i+1);
////               }
//               r++;
           }
            
             Statement st2 = conn.createStatement();
           String sql2 = "select * from gl_mixes";
           ResultSet res2 = st2.executeQuery(sql2);
             while(res2.next()){
               
//               String id = String.valueOf(res.getInt("id"));
               String n = res2.getString("number");
               String product_name = res2.getString("product_name1");
               String article = res2.getString("article_no");
               String stocks = res2.getString("stocks");
               String price = res2.getString("price");
               String sale = res2.getString("sales");
               String tbData[] = {n,product_name,article,stocks,price,sale};
               
                 DefaultTableModel model = (DefaultTableModel)table3.getModel();
                 model.addRow(tbData);
//               for(int i=0; i<col;i++){
////                   rowData[r][i]=res.getString(i+1);
////               }
//               r++;
           }  
             Statement st3 = conn.createStatement();
           String sql3 = "select * from special_flavor";
           ResultSet res3 = st3.executeQuery(sql3);
             while(res3.next()){
               
//               String id = String.valueOf(res.getInt("id"));
               String n = res3.getString("number");
               String product_name = res3.getString("product_name");
               String article = res3.getString("article_no");
               String stocks = res3.getString("stocks");
               String price = res3.getString("price");
               String sale = res3.getString("sales");
               String tbData[] = {n,product_name,article,stocks,price,sale};
               
                 DefaultTableModel model = (DefaultTableModel)table4.getModel();
                 model.addRow(tbData);
//               for(int i=0; i<col;i++){
////                   rowData[r][i]=res.getString(i+1);
////               }
//               r++;
           }  
           
//           String[] columnName = {"ID","Branch Name"};
//           DefaultTableModel model = (DefaultTableModel)table.getModel();
//           model.setDataVector(rowData, columnName);
        
               
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         } 
         
   
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
//    DefaultTableModel model = (DefaultTableModel)table.getModel();
//        int i = table.getSelectedRow();

//      String number = no.getText(); 
      String product = pn.getText();
      String article = an.getText(); 
      String stocks = s.getText();
      String price = p.getText(); 
      String sale = sales.getText();
  
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           if(no.getText().equals("")|| pn.getText().equals("")|| an.getText().equals("")|| s.getText().equals("")|| p.getText().equals("")|| sales.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Please Fill The Blank In The Field List");
           }
            if(selecting.getText().equals("")){
                JOptionPane.showMessageDialog(null,"No Selected Table For Update");
            }  
            else if(selecting.getText().equals("table1")) {
            
            
                 String query = "UPDATE `flavoring` SET product_name=?,article_no=?,stocks=?,price=?,sales=? WHERE id=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (6, no.getText());
            preparedStmt.setString (1, product);
             preparedStmt.setString (2, article);
             preparedStmt.setString (3, stocks);
             preparedStmt.setString (4, price);
             preparedStmt.setString (5, sale);
          
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           JFrame update;
       update = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(update,"Are You Sure You Want To Update This Item?","Close",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
             dispose();
       }
           
           Main m = new Main();
           m.setVisible(true);
           dispose();
//           JOptionPane.showMessageDialog(this, "Item Updated Successfully");
           
         }
            else if(selecting.getText().equals("table2")) {
            
            
                 String query = "UPDATE `food_color` SET color=?,article_no=?,stocks=?,price=?,sales=? WHERE id=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (6, no.getText());
            preparedStmt.setString (1, product);
             preparedStmt.setString (2, article);
             preparedStmt.setString (3, stocks);
             preparedStmt.setString (4, price);
             preparedStmt.setString (5, sale);
          
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           JFrame update;
                update = new JFrame("EXIT");
                 if(JOptionPane.showConfirmDialog(update,"Are You Sure You Want To Update This Item?","Close",
                        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                        Main m = new Main();
                        m.setVisible(true);
                        dispose();

       }      

           
         }
            //table 3
            else if(selecting.getText().equals("table3")) {
            
            
                 String query = "UPDATE `gl_mixes` SET product_name1=?,article_no=?,stocks=?,price=?,sales=? WHERE id=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (6, no.getText());
            preparedStmt.setString (1, product);
             preparedStmt.setString (2, article);
             preparedStmt.setString (3, stocks);
             preparedStmt.setString (4, price);
             preparedStmt.setString (5, sale);
          
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           JFrame update;
                update = new JFrame("EXIT");
                 if(JOptionPane.showConfirmDialog(update,"Are You Sure You Want To Update This Item?","Close",
                        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){

                      dispose();
          }           
           Main m = new Main();
           m.setVisible(true);
           dispose();       
         }     
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }                      
    }//GEN-LAST:event_updateActionPerformed

    private void save_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btn2ActionPerformed
       //table 1
        int i=table1.getSelectedRow();
       if(i>=0){
           DefaultTableModel model = (DefaultTableModel)table1.getModel();
          JFrame delete_btn;
       delete_btn = new JFrame("EXIT");
           if(JOptionPane.showConfirmDialog(delete_btn,"Do you want to to Delete?","MySQL Connector",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
            String id = no.getText(); 
  
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           
                if(no.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Select Item To Delete");
} else {
            
            
          String query = " DELETE FROM flavoring WHERE number=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (1, id);

           JOptionPane.showMessageDialog(this, "Item Deleted Successfully");
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           Main m = new Main();
           m.setVisible(true);
           dispose();
         }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
       }
       }       
       
       // table 2
       
       int ii=table2.getSelectedRow();
       if(ii>=0){
           DefaultTableModel model = (DefaultTableModel)table2.getModel();
          JFrame delete_btn;
       delete_btn = new JFrame("EXIT");
           if(JOptionPane.showConfirmDialog(delete_btn,"Do you want to to Delete?","MySQL Connector",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
            String id1 = no.getText(); 
  
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           
                if(no.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Select Item To Delete");
} else {
            
            
          String query = " DELETE FROM food_color WHERE number=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (1, id1);

           JOptionPane.showMessageDialog(this, "Item Deleted Successfully");
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           Main m = new Main();
           m.setVisible(true);
           dispose();
         }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
       }
       }     
       //table 3
       
        int iii=table3.getSelectedRow();
       if(iii>=0){
           DefaultTableModel model = (DefaultTableModel)table3.getModel();
          JFrame delete_btn;
       delete_btn = new JFrame("EXIT");
           if(JOptionPane.showConfirmDialog(delete_btn,"Do you want to to Delete?","MySQL Connector",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
            String id2 = no.getText(); 
  
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           
                if(no.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Select Item To Delete");
} else {
            
            
          String query = " DELETE FROM gl_mixes WHERE number=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (1, id2);

           JOptionPane.showMessageDialog(this, "Item Deleted Successfully");
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           Main m = new Main();
           m.setVisible(true);
           dispose();
         }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
       }
       }   
       //table 4
       
        int iiii=table4.getSelectedRow();
       if(iiii>=0){
           DefaultTableModel model = (DefaultTableModel)table4.getModel();
          JFrame delete_btn;
       delete_btn = new JFrame("EXIT");
           if(JOptionPane.showConfirmDialog(delete_btn,"Do you want to to Delete?","MySQL Connector",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
            String id3 = no.getText(); 
  
       try{
        String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/inventory_system";
      Class.forName(myDriver);
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
            
           
                if(no.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Select Item To Delete");
} else {
            
            
          String query = " DELETE FROM special_flavor WHERE number=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
             preparedStmt.setString (1, id3);

           JOptionPane.showMessageDialog(this, "Item Deleted Successfully");
           Statement st = conn.createStatement();
           preparedStmt.execute();
           
           Main m = new Main();
           m.setVisible(true);
           dispose();
         }
        }
       }
        catch (ClassNotFoundException | SQLException e)
         {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
         }      
       }
       }     
    }//GEN-LAST:event_save_btn2ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
             int i = table1.getSelectedRow();
        TableModel model = table1.getModel();
         no.setText(model.getValueAt(i,0).toString());
        pn.setText(model.getValueAt(i,1).toString());
        an.setText(model.getValueAt(i,2).toString());
        s.setText(model.getValueAt(i,3).toString());
        p.setText(model.getValueAt(i,4).toString());
        sales.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_table1MouseClicked

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        int i = table2.getSelectedRow();
        TableModel model = table2.getModel();
         no.setText(model.getValueAt(i,0).toString());
        pn.setText(model.getValueAt(i,1).toString());
        an.setText(model.getValueAt(i,2).toString());
        s.setText(model.getValueAt(i,3).toString());
        p.setText(model.getValueAt(i,4).toString());
        sales.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_table2MouseClicked

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
           int i = table3.getSelectedRow();
        TableModel model = table3.getModel();
         no.setText(model.getValueAt(i,0).toString());
        pn.setText(model.getValueAt(i,1).toString());
        an.setText(model.getValueAt(i,2).toString());
        s.setText(model.getValueAt(i,3).toString());
        p.setText(model.getValueAt(i,4).toString());
        sales.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_table3MouseClicked

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
             int i = table4.getSelectedRow();
        TableModel model = table4.getModel();
         no.setText(model.getValueAt(i,0).toString());
        pn.setText(model.getValueAt(i,1).toString());
        an.setText(model.getValueAt(i,2).toString());
        s.setText(model.getValueAt(i,3).toString());
        p.setText(model.getValueAt(i,4).toString());
        sales.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_table4MouseClicked

    private void save_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btn3ActionPerformed
        branches branch = new branches();
        branch.setVisible(true);
        dispose();
    }//GEN-LAST:event_save_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField an;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField no;
    private javax.swing.JTextField p;
    private javax.swing.JTextField pn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JTextField s;
    private javax.swing.JTextField sales;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton save_btn2;
    private javax.swing.JButton save_btn3;
    private javax.swing.JLabel selecting;
    private javax.swing.JComboBox<String> selecting_table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
